# Generated by Django 5.2.7 on 2025-11-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='atarred',
            new_name='starred',
        ),
    ]
