# Generated by Django 5.2.7 on 2025-11-02 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_atarred_blog_starred'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='starred',
            field=models.BooleanField(default=False, verbose_name='Etoile'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(max_length=255, verbose_name='Legende'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de televersement'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Televerseur'),
        ),
    ]
