# Generated by Django 5.2.7 on 2025-11-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_author_alter_blog_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='count_word',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de mot'),
        ),
    ]
