# Generated by Django 5.2.7 on 2025-11-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_author_contributors_blog_contributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Contributor',
            new_name='contributor',
        ),
    ]
