# Generated by Django 5.2.7 on 2025-11-03 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_contributor_blog_contributor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributors',
            new_name='BlogContributors',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contributor',
        ),
        migrations.AddField(
            model_name='blog',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributions', through='blog.BlogContributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
