# Generated by Django 5.2.7 on 2025-11-03 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_contributors_blogcontributors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogContributors',
            new_name='BlogContributor',
        ),
    ]
