# Generated by Django 5.2.7 on 2025-11-03 16:13

from django.db import migrations

def move_author_to_contributors(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    BlogContributor = apps.get_model('blog', 'BlogContributor')
    for blog in Blog.objects.all():
        if blog.author:
            BlogContributor.objects.create(
                contributor=blog.author,
                blog=blog,
                Contribution='Auteur principale'
            )

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_blogcontributors_blogcontributor'),
    ]

    operations = [
        migrations.RunPython(move_author_to_contributors),
    ]
