# Generated by Django 5.2.7 on 2025-11-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontributor',
            name='Contribution',
        ),
        migrations.AlterField(
            model_name='blog',
            name='count_word',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Nombre de mot'),
        ),
        migrations.AddField(
            model_name='blogcontributor',
            name='contribution',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contribution'),
        ),
    ]
