# Generated by Django 5.2.7 on 2025-11-03 14:19

from django.db import migrations


def create_groups(apps, schema_editor):
    User = apps.get_model('comptes', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_photo_permission = Permission.objects.get(codename='add_photo')
    add_blog_permission = Permission.objects.get(codename='add_blog')
    change_blog_permission = Permission.objects.get(codename='change_blog')
    delete_blog_permission = Permission.objects.get(codename='delete_blog')
    view_blog_permission = Permission.objects.get(codename='view_blog')
    view_photo_permission = Permission.objects.get(codename='view_photo')

    creators_permission = [
        add_photo_permission,
        add_blog_permission,
        change_blog_permission,
        delete_blog_permission,
        view_blog_permission,
        view_photo_permission,
    ]

    subscribers_permission = [
        view_blog_permission,
        view_photo_permission,
    ]

    subscribers = Group(name="subscribers")
    subscribers.save()
    subscribers.permissions.set(subscribers_permission)


    creators = Group(name="creators")
    creators.save()
    creators.permissions.set(creators_permission)

    # Optionally, assign existing users to groups here
    for user in User.objects.all():
        if user.role == "CREATOR":
            creators.user_set.add(user)
        else:
            subscribers.user_set.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_user_date_of_birth_alter_user_location'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
